domain: bigbang.dev

networkPolicies:
  enabled: false

clusterAuditor:
  enabled: false

gatekeeper:
  enabled: false

fluentbit:
  enabled: false

jaeger:
  enabled: false

neuvector:
  enabled: false

loki:
  enabled: false

tempo:
  enabled: false

promtail:
  enabled: false

kiali:
  enabled: true

# logging:
#   enabled: false
