#!/bin/bash

# Usage:
# -b   use big M5 instance. Default is t3.2xlarge
# -p   use private IP for security group and k3d cluster
# -m   create k3d cluster with metalLB
# -h   output help

echo
echo -n '⏳ ~/bigbang/docs/assets/scripts/developer/k3d-dev.sh '
echo $@
~/bigbang/docs/assets/scripts/developer/k3d-dev.sh $@
echo '✅ k3d-dev.sh'
